# Generated by Django 2.1 on 2018-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abnormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_up', models.IntegerField()),
                ('coin_down', models.IntegerField()),
                ('amplitude', models.FloatField()),
                ('person', models.FloatField()),
                ('flag', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
